version: '3.8'

services:
  recommender-service:
    build:
      context: .
      dockerfile: Dockerfile.recommendation_service
    container_name: recommender-service
    ports:
      - "8082:8082"
    restart: unless-stopped
